// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: channels.sql

package database

import (
	"context"
)

const checkChannelExists = `-- name: CheckChannelExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE channel_name = $1) AS exists
`

func (q *Queries) CheckChannelExists(ctx context.Context, channelName string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkChannelExists, channelName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
